name: Node GitHub CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Calvin Server
        uses: appleboy/ssh-action@master
        with:
          host: calvin.alkalinethunder.wtf
          username: node-deploy
          key: {{ secrets.SSH_KEY }}
          port: 22
          script: |
            sh ~/backup-uploads.sh
            cd ~/wtf-pwa
            git pull origin master
            npm install --production
            sh ~/restore-uploads.sh
